### ISSUE TITLE
Apply O/SE/DE to the website 

### ISSUE THREAD

**Issue by Mikhail-Zex** [Mikhail-Zex/O.Se.De#3]
### Tasks
- [ ] specify O/SE/DE
- [ ] layout architecture with UML
- [ ] document design rationale
- [ ] design the feedback process
- [ ] design the documentation layout 

### Notes
 - Feedback process is how to work with other repositories and collect feedback,  how to further add in the modifications to O/SE/DE

 - documentation is only to help understand the design/layout of the website for future modification and maintenance purposes
