### ISSUE TITLE
UI/UX design of the website

### ISSUE THREAD

**Issue by Mikhail-Zex** [Mikhail-Zex/O.Se.De#4]
### Tasks
This is about designing the visual/functional layout on the website.

- [x] look through UI/UX practices
- [x] design components (*atomic design*)
- [x] decide on website layout

### Notes
 - website layout is basically which piece of content goes into which page - the distribution of information on different pages.
